---
- hosts: all
  connection: local
  user: "{{lookup('env','USER')}}"
  sudo: yes
  sudo_user: root
  vars:
    _HOSTNAME: vm_ubuntu
  vars_files:
    - ./etc/secret
  tasks:
    - name: Set hostname
      hostname: name={{_HOSTNAME}}
    - name: Copy private keypair
      copy: src=./etc/id_rsa dest=/home/{{lookup('env','USER')}}/.ssh/id_rsa
    - name: Copy apt repo
      copy: src=./etc/apt/sources.list /etc/apt/sources.list
    - name: Ensure software is the lastest version
      apt: name={{item}} state=latest
      with_items:
      - open-vm-tools
      - open-vm-tools-desktop
      - samba
      - git
    - name: Ensure and upload smb.conf
      copy: src=./etc/smb.conf dest=/etc/samba/smb.conf
      notify:
        - restart smb
        - restart nmb
    - name: Ensure firewalld is stopped
      service: name=firewalld state=stopped enabled=false
  handlers:
    - name: restart smb
      service: name=smb state=restarted
    - name: restart nmb
      service: name=nmb state=restarted

